# Generated by Django 5.1.1 on 2025-08-26 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('math_facts', 'Math Facts'), ('anagram_hunt', 'Anagram Hunt')], db_index=True, max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('finished_at', models.DateTimeField()),
                ('final_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-final_score', '-finished_at'],
                'indexes': [models.Index(fields=['game_type', '-final_score'], name='games_games_game_ty_f1f518_idx')],
            },
        ),
    ]
